### ISSUE TITLE
Error Creating a new stack using deploy.sh  because I dont own the s3 bucket deployed by sam

### ISSUE THREAD

**Issue by thanakijwanavit** [OElesin/querypal#10]
Error Message
```
+ sam deploy --stack-name querypal-web-ui --profile default --region us-east-1 --stack-name querypal-web-ui --s3-bucket datafy-data-lake-public-artifacts --template-file build/template.yaml --parameter-overrides pEnv=master pGitHubAccessToken=xxxx pQuerypalAppName=querypal --capabilities CAPABILITY_NAMED_IAM --no-fail-on-empty-changeset

Error: Unable to upload artifact DeployQueryAmplifyAppFxn referenced by CodeUri parameter of DeployQueryAmplifyAppFxn resource.
An error occurred (AccessDenied) when calling the PutObject operation: Access Denied
```

# Suggestion

I can see that this is caused by the hardcoded ```--s3-bucket datafy-data-lake-public-artifacts``` parameter which is owned by the developer. I suggest that this should be a parameter with a random value if not specified and accept a bucket name as a parameter
say `bash deploy.sh --s3-bucket xxxx`. Let me know what you think, i can make a pull request.

**Comment by OElesin** [comment]
@thanakijwanavit , please go ahead.
