### ISSUE TITLE
Deploy script Fails: An error occurred (ParameterNotFound) when calling the GetParameter operation

### ISSUE THREAD

**Issue by thealpha93** [OElesin/querypal#2]
The deploy script fails and gives me the following error
```An error occurred (ParameterNotFound) when calling the GetParameter operation:```
![image](https://user-images.githubusercontent.com/42433480/104451508-a8932300-55c7-11eb-9c26-fe4c25e88dbb.png)

I think it's from this line. It's not getting the`APP_ID`.
```APP_ID=$(sed -e 's/^"//' -e 's/"$//' <<<"$(aws ssm get-parameter --profile $PROFILE --region "$REGION" --name /Querypal/Amplify/AppID --query "Parameter.Value")")```

I don't have an ssm parameter with the name `/Querypal/Amplify/AppID `.

Also mention the right `scopes` for the github token in the documentation.

**Comment by OElesin** [comment]
@thealpha93, thanks for pointing this out. I'll into this shortly.

**Comment by thealpha93** [comment]
@OElesin Thanks.

**Comment by OElesin** [comment]
@thealpha93, fix committed, please pull the latest changes and try again

**Comment by thealpha93** [comment]
@OElesin Thanks. I think it's almost working now. Got past that error. But still the app backend fails the build in cloudformation I guess. I'll look more into it and start a new issue if the issue persists

**Comment by OElesin** [comment]
@thealpha93, great. Please report the new issue and let me look into it. All look good from here by the way!
