### ISSUE TITLE
Issue with amplfy while deploying querypal

### ISSUE THREAD

**Issue by sanjeevpandey19** [OElesin/querypal#6]
Hi @OElesin , 

we are getting this below error in build stage in amplfy job, role which is being used here is having AdministratorFullAcccess. not sure why UserPool is giving error with "InvalidSmsRoleAccessPolicyException" (don't know what does this mean).

Can you help to find out what could an issue here and also your deploy.sh isnt working as specified on https://github.com/OElesin/querypal/issues/3 

```
CREATE_FAILED UserPool                                                          AWS::Cognito::UserPool     Tue Sep 07 2021 14:46:15 GMT+0000 (Coordinated Universal Time) Role does not have permission to publish with SNS (Service: AWSCognitoIdentityProviderService; Status Code: 400; Error Code: InvalidSmsRoleAccessPolicyException; Request ID: 9bee0fd6-22d0-42a9-a062-124753d9ff8b; Proxy: null)
                                 CREATE_FAILED amplify-quarypal-staging-143710-authquerypald06914aa-RNLXZK5UM25B AWS::CloudFormation::Stack Tue Sep 07 2021 14:46:16 GMT+0000 (Coordinated Universal Time) The following resource(s) failed to create: [UserPool].
2021-09-07T14:46:20.368Z [INFO]: 
```

**Comment by OElesin** [comment]
Thanks @sanjeevpandey19. I'll have a look into this and reply shortly. This is also to me.

**Comment by OElesin** [comment]
Maybe have a look at this: https://stackoverflow.com/questions/56637042/amazon-web-services-aws-cognito-error-token-is-not-from-a-supported-provider

**Comment by sanjeevpandey19** [comment]
> Maybe have a look at this: https://stackoverflow.com/questions/56637042/amazon-web-services-aws-cognito-error-token-is-not-from-a-supported-provider

@OElesin this seem little different issue, we are getting on while creating amplify deployment only, not sure what kind of requirement it needs as we have already given Administrator access to the IAM role which is being used in amplify while deploying backend.

**Comment by sanjeevpandey19** [comment]
@OElesin I couldn't understand why we are mapping everything to either us-west-2 or us-east-1 region only for pinpoint app. this was the error in our case, we are using ap-south-1 region only and other are on denied mode. and pinpoint lambda was trying to create pinpoint app in us-west-2 region only.


https://github.com/OElesin/querypal/blob/master/amplify/backend/analytics/querypalpinpoint/pinpoint-cloudformation-template.json#L526

**Comment by OElesin** [comment]
Deployment seems to be resolved. Kindly reopen if you still face the issue.
