### ISSUE TITLE
QuerypalAmplifyApp resource creation, deployment failure

### ISSUE THREAD

**Issue by saadrevcloud** [OElesin/querypal#7]
Hi,
My stack always fails here on creating this resource:
QuerypalAmplifyApp : Resource handler returned message: "Invalid request provided: There was an issue setting up your repository. Please try again later.({"message":"Not Found","documentation_url":"https://docs.github.com/rest/reference/repos#create-a-repository-webhook"}) (Service: Amplify, Status Code: 400, Request ID: 31fd14b5-fabd-408d-afad-1762bde0dc94, Extended Request ID: null)" (RequestToken: XXXXXXX-395e-bef0-59a7-381de886fec2, HandlerErrorCode: InvalidRequest)

It is always successful in creating "AmplifyServiceRole" but fails in creating "QuerypalAmplifyApp". I have also provided the GitHub token with all access.

**Comment by OElesin** [comment]
@saadrevcloud, thanks for pointing this out. I'll have a look.

**Comment by OElesin** [comment]
@saadrevcloud, this is now resolved. Apologies for the delay.
